# Generated by Django 3.2.5 on 2021-07-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxtapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_Data',
            new_name='FileData',
        ),
    ]
