# Generated by Django 3.2.5 on 2021-07-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxtapp', '0003_rename_filedata_file_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_data',
            old_name='filesize',
            new_name='file_size',
        ),
    ]
