# Generated by Django 3.2.5 on 2021-07-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxtapp', '0004_rename_filesize_file_data_file_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_Data',
        ),
    ]
