# Generated by Django 3.2.5 on 2021-07-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxtapp', '0010_file_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_Data',
        ),
    ]
