# Generated by Django 3.2.5 on 2021-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtapp', '0024_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_data',
            name='full_data',
            field=models.CharField(max_length=2000),
        ),
    ]
