# Generated by Django 3.2.5 on 2021-07-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtapp', '0025_alter_file_data_full_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_data',
            name='full_data',
            field=models.TextField(),
        ),
    ]
