# Generated by Django 3.2.5 on 2021-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtapp', '0028_file_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_data',
            name='full_data',
        ),
        migrations.AlterField(
            model_name='file_data',
            name='content',
            field=models.TextField(),
        ),
    ]
